# Site Settings
title: Ivisionlab
tagline: Ivision
email: your-email@domain.com
description: >
  Ivision lab
baseurl: ""
url: "https://www.ivisionlab.ufba.br"
permalink: /:categories/:title.html
#favicon: /path/to/favicon.png


paginate: 5
paginate_path: "/workshops/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Ivision"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: false

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu